openapi: 3.1.0
info:
  title: Brkrs Gameplay Control API (Conceptual)
  version: "0.1.0"
  description: |
    Conceptual contract describing the ECS-driven respawn and level-flow actions.
    Endpoints mirror in-game events and provide a stable shape for telemetry or tooling.
servers:
  - url: https://game.local/api
paths:
  /sessions/{sessionId}/life-loss:
    post:
      summary: Notify the engine that a ball crossed the lower goal and queue respawn.
      tags: [Respawn]
      parameters:
        - $ref: '#/components/parameters/SessionId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LifeLossEvent'
      responses:
        '202':
          description: Respawn scheduled.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespawnTicket'
  /sessions/{sessionId}/respawns/{ticketId}/complete:
    post:
      summary: Confirm that paddle growth finished and ball can unfreeze.
      tags: [Respawn]
      parameters:
        - $ref: '#/components/parameters/SessionId'
        - name: ticketId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RespawnComplete'
      responses:
        '204':
          description: Respawn marked complete.
  /sessions/{sessionId}/levels/{levelId}/advance:
    post:
      summary: Begin fade overlay and schedule the next level load after brick-clear.
      tags: [LevelFlow]
      parameters:
        - $ref: '#/components/parameters/SessionId'
        - $ref: '#/components/parameters/LevelId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LevelAdvanceRequest'
      responses:
        '202':
          description: Level advance in progress.
  /sessions/{sessionId}/levels/{levelId}/restart:
    post:
      summary: Player requested a restart (e.g., pressed the `R` key).
      tags: [LevelFlow]
      parameters:
        - $ref: '#/components/parameters/SessionId'
        - $ref: '#/components/parameters/LevelId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LevelRestartRequest'
      responses:
        '202':
          description: Restart scheduled.
components:
  parameters:
    SessionId:
      name: sessionId
      in: path
      required: true
      schema:
        type: string
      description: Gameplay session identifier.
    LevelId:
      name: levelId
      in: path
      required: true
      schema:
        type: string
      description: Matches `level_id` from `LevelDefinition`.
  schemas:
    Vec3:
      type: object
      properties:
        x:
          type: number
        y:
          type: number
        z:
          type: number
      required: [x, y, z]
    LifeLossEvent:
      type: object
      properties:
        ballEntity:
          type: string
          description: ECS entity ID (debug).
        paddleEntity:
          type: string
        cause:
          type: string
          enum: [LowerGoal, Manual, Scripted]
        timestampMs:
          type: integer
          format: int64
      required: [ballEntity, paddleEntity, cause, timestampMs]
    RespawnTicket:
      type: object
      properties:
        ticketId:
          type: string
        scheduledAtMs:
          type: integer
          format: int64
        respawnDelayMs:
          type: integer
          format: int64
        paddleGrowthMs:
          type: integer
          format: int64
        spawnPoints:
          type: array
          items:
            $ref: '#/components/schemas/SpawnPoint'
      required: [ticketId, scheduledAtMs, respawnDelayMs, paddleGrowthMs, spawnPoints]
    SpawnPoint:
      type: object
      properties:
        kind:
          type: string
          enum: [Paddle, Ball]
        translation:
          $ref: '#/components/schemas/Vec3'
        facing:
          $ref: '#/components/schemas/Vec3'
      required: [kind, translation]
    RespawnComplete:
      type: object
      properties:
        completedAtMs:
          type: integer
          format: int64
      required: [completedAtMs]
    LevelAdvanceRequest:
      type: object
      properties:
        clearedBricks:
          type: integer
          minimum: 0
        totalBricks:
          type: integer
          minimum: 0
        fadeDurationMs:
          type: integer
          minimum: 0
        gravityOverride:
          $ref: '#/components/schemas/Vec3'
      required: [clearedBricks, totalBricks, fadeDurationMs]
    LevelRestartRequest:
      type: object
      properties:
        reason:
          type: string
          enum: [PlayerInput, Scripted]
        requestedAtMs:
          type: integer
          format: int64
      required: [reason, requestedAtMs]
    LevelProgress:
      type: object
      properties:
        currentLevel:
          type: integer
          minimum: 0
        lives:
          type: integer
          minimum: 0
        pendingRespawn:
          type: boolean
        gravity:
          $ref: '#/components/schemas/Vec3'
      required: [currentLevel, lives, pendingRespawn]
